function ds = fanUnboundedFace(r, x, y)
% fanUnboundedFace  Cover an UNBOUNDED convex polyhedral face by pieces Step 1 can envelope.
%
% [input]  r    : region, an unbounded polyhedron with affine facets and a POINTED recession
%                 cone (region.recessionRays reports 'ray' or 'wedge').
% [output] ds   : 1xN cell of `domain`, whose union is exactly r and each of which is a
%                 TRIANGLE, a HALF-STRIP (conv{v1,vn} + cone(d)) or a WEDGE (v + cone(da,db)).
%
% WHY A COVER IS ENOUGH, AND WHY IT MUST NOT BE A SUPERSET. The convex envelope does NOT
% decompose over a cover -- co(q|P) is generally strictly below co(q|P_i) on P_i. The
% CONJUGATE does, because a sup over a union is the max of the sups:
%     (q|_P)* = max_i (q|_{P_i})*   and   (q|_{P_i})* = (co q|_{P_i})*.
% That is exactly the decomposition cPLQ already relies on -- it is why plq.triangulate exists
% at all, and plq.maximum already takes the max across pieces. The price is that each piece
% must be a SUBSET of r: a superset would inflate its own sup and hence the max.
%
% THE FAN. Write r = conv{v1,...,vn} + cone(da,db) with the finite vertices in boundary order,
% da the ray leaving v1 and db the ray leaving vn. Fanning from v1 over every boundary piece
% not incident to v1 gives
%     r = [v1 + cone(da,db)]                       the wedge at the apex
%       U [conv{v1,vn} + cone(db)]                 the cone from v1 over the far RAY
%       U [conv{v1,vi,vi+1} : i = 2..n-1]          the cone from v1 over each bounded edge,
% and that is the whole of r. Proof: take p in r, p ~= v1, and follow the ray from v1 through
% p. Either it leaves r through a boundary piece B not containing v1 -- then p lies in the cone
% from v1 over B -- or it never leaves, in which case p - v1 is a recession direction, i.e.
% p - v1 lies in cone(da,db) and p lies in the apex wedge. Each piece is generated by points
% and directions of r, so each is a subset of r, as required above.
%
% The three shapes are exactly the ones an AFFINE envelope is rigid on -- 3 conditions for the
% 3 degrees of freedom of an affine function in the plane: a triangle gives 3 vertex values, a
% wedge gives 1 vertex value plus 2 directional derivatives, a half-strip gives 2 vertex values
% plus 1 directional derivative (its two rays are parallel and impose the same condition). See
% convEnvUnbounded, which consumes exactly these.
%
% Degenerate members are dropped rather than emitted: with a single finite vertex the
% half-strip collapses to a ray, and with da parallel to db the wedge collapses to a ray.
% Neither has interior, so neither contributes to a sup.

    [D, kind] = r.recessionRays;
    if strcmp(kind, 'nonpointed')
        ds = cutNonPointed(r, x, y);        % half-plane / slab / plane: cut it pointed first
        return
    end
    if ~ismember(kind, {'ray','wedge'})
        error('fanUnboundedFace:notPointed', ...
            ['fanUnboundedFace needs a pointed unbounded face; recessionRays reports ''%s''. ' ...
             'A bounded face belongs on plq_1p.triangulate''s existing path.'], kind);
    end

    [nP, px, py] = r.finiteVertices;
    if nP < 1
        error('fanUnboundedFace:noVertex', ...
            ['fanUnboundedFace needs at least one finite vertex to fan from; this face has ' ...
             'none, so it is not pointed in the sense the fan requires.']);
    end
    V = double([px(:), py(:)]);
    V = dedupeRows(V);
    nP = size(V,1);

    if strcmp(kind, 'ray')
        da = D(1,:); db = D(1,:);          % a half-strip: both unbounded edges share a direction
    else
        da = D(1,:); db = D(2,:);
    end

    % Base vertex of a ray: the extreme vertex of the face in that direction. For an edge of a
    % pointed polyhedron that is a single vertex, which is what makes argmax the right rule.
    [~, ia] = max(V * da');
    [~, ib] = max(V * db');
    if strcmp(kind,'ray') && nP >= 2
        % Both unbounded edges point the same way, so the argmax above is a tie between the two
        % base vertices of the half-strip; take them apart along the perpendicular instead.
        p = [-da(2), da(1)];
        [~, ia] = min(V * p');
        [~, ib] = max(V * p');
    end

    ord = boundaryOrder(V, ia, ib);
    va = V(ord(1),:); vb = V(ord(end),:);

    ds = {};
    % (1) the apex wedge, unless da and db are the same ray
    if norm(da - db) > 1e-9
        ds{end+1} = wedgeDomain(va, da, db, x, y);
    end
    % (2) the cone from the apex over the far ray: a half-strip, unless the apex IS the base
    if norm(va - vb) > 1e-9
        ds{end+1} = halfStripDomain(va, vb, db, x, y);
    end
    % (3) the cone from the apex over each bounded edge
    for i = 2:numel(ord)-1
        t = [va; V(ord(i),:); V(ord(i+1),:)];
        if abs(det([t(2,:)-t(1,:); t(3,:)-t(1,:)])) < 1e-12
            continue                        % degenerate: three collinear vertices span no area
        end
        ds{end+1} = domain(t, x, y); %#ok<AGROW>
    end
end

% ------------------------------------------------------------------------------------------
function ds = cutNonPointed(r, x, y)
% Cover a face whose recession cone contains a LINE by pieces whose recession cones are POINTED,
% and fan each of those. Handles the two shapes the fan itself cannot start on -- a HALF-PLANE
% (recession cone a half-plane) and a SLAB (recession cone a line) -- and, by recursing, the
% whole plane.
%
% WHY A CUT IS THE WHOLE FIX, AND WHY IT NEEDS NO NEW ENVELOPE THEORY. The fan needs an apex, and
% a non-pointed face has none: it recedes along BOTH +t and -t for some direction t, so no vertex
% dominates. Cutting transversally to t removes exactly that. Write L for the lineality space of
% the recession cone R = {d : A d <= 0}. R contains a line precisely when rank(A) < 2 (which is
% what made recessionRays report 'nonpointed'), so every nonzero row of A is parallel to a single
% normal a, and L is spanned by t = (-a2, a1). Cutting along {t'z = 0} gives
%       P = (P n {t'z <= 0}) u (P n {t'z >= 0}),
% and the half's recession cone is R n {t'd <= 0} (resp. >= 0), which no longer contains a line:
% a line in it would need both d and -d, forcing t'd = 0, and in the plane the only such
% directions are the ones the cut just made extreme. A half-plane therefore becomes two wedges and
% a slab becomes two half-strips -- both shapes convEnvUnbounded already handles exactly.
%
% The cut is a COVER of the same kind fanUnboundedFace's own header justifies: a sup over a union
% is the max of the sups, and each half is a SUBSET of the face, so nothing is over-claimed. The
% two halves overlap on the cut line, which has no interior and so contributes no sup of its own.
%
% The cut POSITION is free -- the face recedes along both +t and -t, so every half is nonempty for
% any offset -- and 0 is chosen because it keeps the new constraint's coefficients exactly those
% of t. That matters for the same reason recessionRays returns rational directions rather than
% (cos,sin): a 6.1e-17 where a 0 belongs turns `x <= 0` into a different, still non-pointed,
% half-plane. t is likewise scaled by its own largest entry, never normalized to unit length.
%
% Recursion terminates in at most two levels in the plane: each cut strictly drops the dimension
% of the lineality space, from 2 (no constraints at all) to 1 to 0.
    [A, ~, lin] = r.linearForm;
    if ~all(lin)
        error('fanUnboundedFace:nonAffineFacet', ...
            ['cutting a non-pointed face needs every facet affine: a curved facet''s recession ' ...
             'behaviour is not a half-plane, so its lineality direction is not read off A.']);
    end
    tolA = 1e-9 * max(1, max(abs(A(:))));
    a = [];
    for j = 1:size(A,1)
        if norm(A(j,:)) > tolA, a = A(j,:); break, end
    end
    if isempty(a)
        t = [1 0];                      % no constraints: the whole plane, cut it anywhere
    else
        t = [-a(2), a(1)];              % perpendicular to the single constraint normal
    end
    t = t / max(abs(t));                % O(1) and exactly rational when a is; never unit-length

    vars = r.vars;
    g = t(1)*vars(1) + t(2)*vars(2);

    % The halves are built with region.plus, which IS intersection (it unions the inequality
    % lists and dedupes) -- not by pulling r.ineqs apart and rebuilding. Reading that property
    % from outside the class does not give the constraint count linearForm sees internally, and
    % a cut built from a miscounted list silently loses a facet: the slab's half came back
    % 'bounded' from recessionRays, i.e. with the far constraint gone.
    ds = {};
    for sgn = [1 -1]
        half = r + region(sgn*g, vars);
        ds = [ds, fanUnboundedFace(half, x, y)]; %#ok<AGROW>
    end
end

function V = dedupeRows(V)
    keep = true(size(V,1),1);
    for i = 2:size(V,1)
        for j = 1:i-1
            if keep(j) && norm(V(i,:) - V(j,:)) < 1e-9, keep(i) = false; break, end
        end
    end
    V = V(keep,:);
end

function ord = boundaryOrder(V, ia, ib)
% The finite vertices from ia round to ib along the BOUNDED part of the boundary.
%
% The finite vertices are in convex position (they are the vertices of conv V, whose bounded
% edges are exactly the bounded facets of the face), so sorting them by angle about their
% centroid recovers the boundary cycle. In that cycle ia and ib are adjacent -- the edge
% joining them is the one "open side" of conv V that is not a facet of the face -- so the
% boundary chain is the cycle traversed the OTHER way round.
    n = size(V,1);
    if n == 1, ord = 1; return, end
    if n == 2, ord = [ia, ib]; return, end
    ctr = mean(V,1);
    [~, cyc] = sort(atan2(V(:,2)-ctr(2), V(:,1)-ctr(1)));
    pa = find(cyc == ia); pb = find(cyc == ib);
    if isempty(pa) || isempty(pb)
        error('fanUnboundedFace:baseVertex', 'ray base vertex is not among the finite vertices');
    end
    fwd = mod(pb - pa, n);
    if fwd == 1
        ord = cyc(mod((pa-1) - (0:n-1), n) + 1);       % ia and ib adjacent forwards: go backwards
    elseif mod(pa - pb, n) == 1
        ord = cyc(mod((pa-1) + (0:n-1), n) + 1);       % adjacent backwards: go forwards
    else
        error('fanUnboundedFace:baseVertex', ...
            ['the two ray base vertices are not adjacent in the vertex cycle (%d apart of %d), ' ...
             'so this face is not the pointed polyhedron the fan assumes.'], fwd, n);
    end
    ord = ord(:)';
    if ord(end) ~= ib
        error('fanUnboundedFace:baseVertex', 'boundary chain does not end at the second ray base');
    end
end

function d = wedgeDomain(v, d1, d2, x, y)
% v + cone(d1,d2), as the two half-planes whose boundary lines carry the rays.
    g = [halfPlaneThrough(v, d1, d2, x, y), halfPlaneThrough(v, d2, d1, x, y)];
    d = domain();
    d = d.domainEdge(g, [x, y]);
end

function d = halfStripDomain(v1, v2, dir, x, y)
% conv{v1,v2} + cone(dir): the two rays, plus the base edge [v1,v2] with the strip above it.
    g = [halfPlaneThrough(v1, dir, v2 - v1, x, y), ...
         halfPlaneThrough(v2, dir, v1 - v2, x, y), ...
         halfPlaneThrough(v1, v2 - v1, dir,   x, y)];
    d = domain();
    d = d.domainEdge(g, [x, y]);
end

function g = halfPlaneThrough(v, along, inward, x, y)
% The half-plane whose boundary is the line through v with direction `along`, on the side
% `inward` points to, written as g <= 0 the way region stores its inequalities.
    n = [-along(2), along(1)];
    if n * inward(:) > 0
        n = -n;
    end
    g = n(1)*(x - v(1)) + n(2)*(y - v(2));
end
