import QuaConProof.Quad
import QuaConProof.Conic
import QuaConProof.QuaPol
import QuaConProof.Bary
import QuaConProof.Candidates
import QuaConProof.Selection
import QuaConProof.FrankWolfe
import QuaConProof.Convexity
import QuaConProof.QuaCon
import QuaConProof.Shapes
import QuaConProof.Realization
import QuaConProof.Witness
import QuaConProof.QuaPar
import QuaConProof.Rational
