% 5d differential: new isFeasible vs the pairwise-solve original, plus the property both must
% respect -- a region with a witness point is NOT empty.
cd(getenv('CCA2DIR')); addpath(getenv('SPDIR'));
warning('off','symbolic:sym:isAlways:TruthUnknown');
x = sym('x'); y = sym('y');
cases = { ...
  {'triangle',            region([-x, -y, x+y-2], [x y]),                    true }, ...
  {'empty by 3, not 2',   region([1-x, 1-y, x+y-1], [x y]),                  false}, ...
  {'opposite halfplanes', region([x-1, 2-x], [x y]),                         false}, ...
  {'g and -g',            region([x-1, 1-x], [x y]),                         false}, ...
  {'conic + lines',       region([x^2-y, y-1, -x-1], [x y]),                 true }, ...
  {'half lens',           region([(x+y)^2-4*x, -x, -y], [x y]),              true }, ...
  {'piece 9',             region([16*x-4*x*y-x^2-4*y^2, -x-2*y, (2*y)/3-x-sym(1)/3, x+2*y-2], [x y]), true}, ...
  {'conic vs line, disjoint', region([x^2+y^2-1, x-5], [x y]),               false}, ...
  {'unbounded wedge',     region([-x, -y], [x y]),                           true } };
fprintf('%-28s %-8s %-8s %s\n', 'case', 'new', 'want', 'verdict');
bad = 0;
for k = 1:numel(cases)
    nm = cases{k}{1}; r = cases{k}{2}; want = cases{k}{3};
    got = r.isFeasible;
    tag = 'ok';
    if got ~= want, tag = 'MISMATCH'; bad = bad + 1; end
    fprintf('%-28s %-8d %-8d %s\n', nm, got, want, tag);
end
fprintf('\nmismatches %d of %d\n', bad, numel(cases));
